### ISSUE TITLE
Version 2.0.0 Checklist

### ISSUE THREAD

**Issue by tylucaskelley** [greylocklabs/teapot#2]
There are several things that should be done for a nice 2.0.0 release:

- [x] Create a base `HTTPError` class for `ClientError`, `ServerError`, and associated subclasses to extend
- [x] Break up test suite into smaller files
- [x] Decide on support for Flow or TypeScript (or neither)
- [ ] Deprecate '@greylocklabs/http' and publish as 'node-teapot'
- [ ] Create a logo
- [x] Reduce size of npm package by providing files array

**Comment by tylucaskelley** [comment]
decided no on debug; doesn't really make sense for small utility library

**Comment by tylucaskelley** [comment]
settled on teapot for name
